# Generated by Django 5.2.8 on 2025-12-19 22:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videos', '0001_initial'),
        # ('voice_cloning', '0002_rename_voice_cloni_video_i_idx_voice_cloni_video_i_cb9b81_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LipSyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_video_path', models.CharField(help_text='Path to original video file', max_length=500)),
                ('input_audio_path', models.CharField(help_text='Path to cloned audio file', max_length=500)),
                ('lip_synced_video_path', models.CharField(blank=True, help_text='Path to lip-synced video (before composition)', max_length=500)),
                ('final_video_path', models.CharField(blank=True, help_text='Path to final composed video', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=85, help_text='Processing progress percentage (85-100)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.FloatField(default=0.0, help_text='Total processing time in seconds')),
                ('video_duration', models.FloatField(default=0.0, help_text='Duration of output video in seconds')),
                ('use_gpu', models.BooleanField(default=False, help_text='Whether GPU was used for processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lip_sync_jobs', to='videos.video')),
                # ('voice_cloning_task', models.ForeignKey(blank=True, help_text='The voice cloning task that produced the audio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lip_sync_jobs', to='voice_cloning.voicecloningtask')),
            ],
            options={
                'verbose_name': 'Lip Sync Job',
                'verbose_name_plural': 'Lip Sync Jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['video', '-created_at'], name='lip_sync_li_video_i_883f91_idx'), models.Index(fields=['status'], name='lip_sync_li_status_20acac_idx')],
            },
        ),
    ]
