# Generated by Django 5.2.8 on 2025-12-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='translated_audio_path',
            field=models.CharField(blank=True, help_text='Path to translated audio file', max_length=500, null=True),
        ),
    ]
