# Generated by Django 6.0 on 2026-01-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_translated_audio_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='original_video',
            field=models.FileField(max_length=500, upload_to='videos/original/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='processed_video',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='videos/processed/%Y/%m/%d/'),
        ),
    ]
